spring:
  application:
    name: blog-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:postgres}
    password: ${DB_PASSWORD:password}
    username: ${DB_USERNAME:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
token-issuer:
  base-url: ${TOKEN_ISSUER_BASE_URL:http://localhost:8092}
  token-validation-endpoint: ${TOKEN_VALIDATION_ENDPOINT:/api/v1/token/validate}
