package ua.aleksenko.blogservice.selenium;// Generated by Selenium IDE

import static org.junit.jupiter.api.Assertions.assertTrue;

import java.time.Duration;
import java.util.UUID;
import lombok.SneakyThrows;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

public class CreatePostTest {

  private WebDriver driver;

  @BeforeEach
  public void setUp() {
    System.setProperty("webdriver.http.factory", "jdk-http-client");
    System.setProperty("webdriver.chrome.driver", "chromedriver.exe");
    driver = new ChromeDriver();
  }

  @AfterEach
  public void tearDown() {
    driver.quit();
  }

  @SneakyThrows
  @Test
  public void createPost() {
    final String postName = UUID.randomUUID().toString();

    driver.get("http://localhost:4200/login");
    driver.manage().window().setSize(new Dimension(968, 1039));
    driver.findElement(By.name("username")).click();
    driver.findElement(By.name("username")).sendKeys("aleks.artem24@gmail.com");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("aleks.artem24@gmail.com");
    driver.findElement(By.cssSelector(".field:nth-child(3) > input")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".field:nth-child(3) > input"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(
          By.cssSelector(".mdc-button:nth-child(4) > .mat-mdc-button-touch-target"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(
          By.cssSelector(".mdc-button:nth-child(5) > .mat-mdc-button-touch-target"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(
          By.cssSelector(".mat-toolbar > .mdc-button:nth-child(3) > .mat-mdc-button-touch-target"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.xpath("//span[contains(.,\'Create New Post\')]")).click();
    driver.findElement(By.cssSelector(".ng-tns-c3736059725-0 .mat-mdc-form-field-infix")).click();
    driver.findElement(By.id("mat-input-0")).sendKeys(postName);
    driver.findElement(By.cssSelector(".ng-tns-c3736059725-1 .mat-mdc-form-field-infix")).click();
    driver.findElement(By.id("mat-input-1")).sendKeys("Image");
    driver.findElement(By.id("mat-input-2")).click();
    driver.findElement(By.id("mat-input-2")).sendKeys("Content");
    driver.findElement(By.cssSelector(".mat-mdc-form-field-type-mat-chip-grid")).click();
    driver.findElement(By.id("mat-mdc-chip-list-input-0")).click();
    driver.findElement(By.id("mat-mdc-chip-list-input-0")).sendKeys("tags1");
    driver.findElement(By.id("mat-mdc-chip-list-input-0")).sendKeys(Keys.ENTER);
    {
      WebElement element = driver.findElement(By.cssSelector(".ng-dirty .mdc-button__label"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }

    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }

    new WebDriverWait(driver, Duration.ofSeconds(10))
        .until(ExpectedConditions.elementToBeClickable(By.id("create-new-post"))).click();

    Thread.sleep(1000);
    WebElement post = driver.findElement(By.id(postName));
    assertTrue(post.isDisplayed(), "Post is not present");
  }
}
