package ua.aleksenko.blogservice.selenium;// Generated by Selenium IDE

import static org.junit.jupiter.api.Assertions.assertEquals;

import lombok.SneakyThrows;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;
import ua.aleksenko.blogservice.selenium.pages.LoginPage;


public class EditProfileTest {

  private WebDriver driver;

  @BeforeEach
  public void setUp() {
    System.setProperty("webdriver.http.factory", "jdk-http-client");
    System.setProperty("webdriver.chrome.driver", "chromedriver.exe");
    driver = new ChromeDriver();
  }

  @AfterEach
  public void tearDown() {
    driver.quit();
  }

  @SneakyThrows
  @Test
  public void profile() {
    // Init login page via Page Object Pattern
    LoginPage loginPage = new LoginPage(driver);

    driver.get("http://localhost:4200/login");
    driver.manage().window().setSize(new Dimension(1936, 1056));
    loginPage.getUserName().click();
    loginPage.getUserName().sendKeys("aleks.artem24@gmail.com");
    loginPage.getPassword().click();
    {
      WebElement element = driver.findElement(
          By.cssSelector(".mdc-button:nth-child(5) > .mat-mdc-button-touch-target"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(
          By.cssSelector(".mdc-button:nth-child(5) > .mdc-button__label"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.xpath("//span[contains(.,\'Profile\')]")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.name("age")).click();
    driver.findElement(By.name("age")).sendKeys("22");
    driver.findElement(By.name("gender")).click();
    driver.findElement(By.name("gender")).sendKeys("Male");
    driver.findElement(By.name("address")).click();
    driver.findElement(By.name("address")).sendKeys("MyAddress");
    driver.findElement(By.name("website")).click();
    driver.findElement(By.name("website")).sendKeys("Google");
    driver.findElement(By.cssSelector("button:nth-child(1)")).click();

    Thread.sleep(2000);
    WebElement popUp = driver.findElement(By.id("cdk-overlay-0"));
    assertEquals(popUp.getText(), "You profile successfully updated!\nOk");
  }
}
