package ua.aleksenko.blogservice.selenium;// Generated by Selenium IDE

import static org.junit.jupiter.api.Assertions.assertTrue;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import ua.aleksenko.blogservice.selenium.pages.LoginPage;

public class LoginTest {

  private WebDriver driver;

  @BeforeEach
  public void setUp() {
    System.setProperty("webdriver.http.factory", "jdk-http-client");
    System.setProperty("webdriver.chrome.driver", "chromedriver.exe");
    driver = new ChromeDriver();
  }

  @AfterEach
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void login() {
    // Init login page via Page Object Pattern
    LoginPage loginPage = new LoginPage(driver);

    driver.get("http://localhost:4200/login");
    driver.manage().window().setSize(new Dimension(1936, 1056));
    loginPage.getUserName().click();
    loginPage.getUserName().sendKeys("aleks.artem24@gmail.com");
    loginPage.getPassword().click();
    loginPage.getPassword().sendKeys("aleks.artem24@gmail.com");
    loginPage.getLoginButton().click();
    WebDriverUtils.makeScreenShot(driver, "Login");
    WebElement logOutButton = driver.findElement(By.cssSelector(
        "body > app-root > mat-toolbar > button:nth-child(6) > span.mdc-button__label"));
    assertTrue(logOutButton.isDisplayed(), "Button is not present");
  }


}
