package ua.aleksenko.blogservice.selenium;// Generated by Selenium IDE

import static org.junit.jupiter.api.Assertions.assertTrue;

import java.util.UUID;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;

public class RegisterNewUserTest {

  private WebDriver driver;

  @BeforeEach
  public void setUp() {
    System.setProperty("webdriver.http.factory", "jdk-http-client");
    System.setProperty("webdriver.chrome.driver", "chromedriver.exe");
    driver = new ChromeDriver();
  }

  @AfterEach
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void registerNewUser() {
    driver.get("http://localhost:4200/login");
    driver.findElement(By.cssSelector(".signup-link:nth-child(4)")).click();
    driver.findElement(By.linkText("Signup now")).click();
    driver.findElement(By.name("first_name")).click();
    driver.findElement(By.name("first_name")).sendKeys("Aaaa");
    driver.findElement(By.name("last_name")).click();
    driver.findElement(By.name("last_name")).sendKeys("Aaaaaaa");
    driver.findElement(By.name("username")).click();
    driver.findElement(By.name("username")).sendKeys(UUID.randomUUID() + "@gmail.com");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("123456");
    driver.findElement(By.cssSelector(".field:nth-child(5) > input")).click();
    driver.manage().window().setSize(new Dimension(968, 1039));
    WebElement logOutButton = driver.findElement(By.cssSelector(
        "body > app-root > mat-toolbar > button:nth-child(6) > span.mdc-button__label"));
    assertTrue(logOutButton.isDisplayed(), "Button is not present");
  }
}
