package ua.aleksenko.blogservice.selenium;// Generated by Selenium IDE

import static org.junit.jupiter.api.Assertions.assertTrue;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;

public class ResetPasswordTest {

  private WebDriver driver;

  @BeforeEach
  public void setUp() {
    System.setProperty("webdriver.http.factory", "jdk-http-client");
    System.setProperty("webdriver.chrome.driver", "chromedriver.exe");
    driver = new ChromeDriver();
  }

  @AfterEach
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void resetPassword() {
    driver.get("http://localhost:4200/login");
    driver.manage().window().setSize(new Dimension(968, 1039));
    driver.findElement(By.linkText("Restore now")).click();
    driver.findElement(By.name("username")).click();
    driver.findElement(By.name("username")).sendKeys("aleks.artem24@gmail.com");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("aleks.artem24@gmail.com");
    driver.findElement(By.cssSelector(".field:nth-child(3) > input")).click();
    WebElement logOutButton = driver.findElement(By.cssSelector(
        "body > app-root > mat-toolbar > button:nth-child(6) > span.mdc-button__label"));
    assertTrue(logOutButton.isDisplayed(), "Button is not present");
  }
}
